zsh: set the hm alias to home-manager in PATH
When executed via ${pkgs.home-manager}/bin/home-manager, it fails with
the following message:

error: The option `services.gpg-agent.maxCacheTtl' defined in
`/home/kalbasit/.config/nixpkgs/home.nix' does not exist.